### ISSUE TITLE
Discussion: synonyms

### ISSUE THREAD

**Issue by NilsEnevoldsen** [gmac/menagerie#17]
I think there should be some concept of tags that are synonyms. For example, `aristocrat`, `sac outlet`, `sacrifice outlet`. Tagging as one should tag as all. However, I don't know how this should work.

**Comment by NilsEnevoldsen** [comment]
Related concept: tag hierarchies. If art has a "squirrel", it necessarily has an "animal".

**Comment by gmac** [comment]
I think this relates to the issue described in #21, and might be solved by a similar approach.

My thinking here would be to establish a table for related terms that each hook to a tag. We could then normalize submissions to use the official tag in place of established synonyms.

I'd also note that this is a big reason why tags are editable on the admin side so that they can be rewritten during acceptance to match preferred taxonomy.

**Comment by jhallbachner** [comment]
Yeah, I think the way to go here is to have a canonical tag (so that everything is stored consistently on the data side) but then have a stored list of synonyms that the search API automatically dereferences. When someone's tagging the verify screen could gray out the option to set the tag as entered and then list the canonical one with the text "synonym" as the available choice so the user knows what's happening.

**Comment by gmac** [comment]
This is done! Tags may now be assigned as aliases for other tags... this keeps the alias tag active within the tag graph (so it remains searchable) but forwards navigation on to its source, and validates that aliases are converted to their canonical tag name during submission.
